### ISSUE TITLE
ui: landing page

### ISSUE THREAD

**Issue by karetsu** [datasciencecampus/zygerria#78]
The landing page formatting could be improved. 

<img width="1570" alt="landing" src="https://cloud.githubusercontent.com/assets/20670199/26352308/1ce2c744-3fb3-11e7-9a8b-1872e6332e98.png">

suggested ui points:

* space out the DSC and mango logos, perhaps make them into a column instead of floated and include some kind of precurosry "brought to you by:". 
* the logos should be clickable links to the homepages for each of the 'business partners'
* that last update text should be at the bottom as a footer
* decide on the final text to include

**Comment by nathaneastwood** [comment]
We have now had an official request from CO.

- [ ] Overall name should be changed from 'Welcome to the...' to 'Employment Prospects Data Visualisation Tool'
- [ ] Remove the middle text in between title and logos and replace with attached file. There is also a table that can be put in as is or within a similarly formatted table.

[Employment Prospects Introduction.docx](https://github.com/datasciencecampus/zygerria/files/1074572/Employment.Prospects.Introduction.docx)
