### ISSUE TITLE
ui: continuity of selection

### ISSUE THREAD

**Issue by karetsu** [datasciencecampus/zygerria#79]
When selecting an area in maps it might be worthwhile having that pre-loaded in the time series to show you how that(those) area(s) have changed over time - something that is not available in the map. 

It needs contrasting with the fact that the maps allow selection of 15 LAs but the time series only allows 5. How to deal with this may be non-trivial (where 15 time series make it look ugly and crap).

**Comment by nathaneastwood** [comment]
I suspect that the time series will not remain within the app. We do not currently have the data over time for all variables and this isn't the main focus of the app.
